whenever sqlerror exit
insert into os_variants values (id_seq.nextval, 'almalinux8', 'AlmaLinux 8');
insert into os_variants values (id_seq.nextval, 'almalinux9', 'AlmaLinux 9');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.10', 'Alpine Linux 3.10');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.11', 'Alpine Linux 3.11');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.12', 'Alpine Linux 3.12');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.13', 'Alpine Linux 3.13');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.14', 'Alpine Linux 3.14');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.15', 'Alpine Linux 3.15');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.16', 'Alpine Linux 3.16');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.17', 'Alpine Linux 3.17');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.18', 'Alpine Linux 3.18');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.19', 'Alpine Linux 3.19');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.20', 'Alpine Linux 3.20');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.5', 'Alpine Linux 3.5');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.6', 'Alpine Linux 3.6');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.7', 'Alpine Linux 3.7');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.8', 'Alpine Linux 3.8');
insert into os_variants values (id_seq.nextval, 'alpinelinux3.9', 'Alpine Linux 3.9');
insert into os_variants values (id_seq.nextval, 'alt.p10', 'ALT p10 StarterKits');
insert into os_variants values (id_seq.nextval, 'alt.p11', 'ALT p11 StarterKits');
insert into os_variants values (id_seq.nextval, 'alt.p8', 'ALT p8 StarterKits');
insert into os_variants values (id_seq.nextval, 'alt.p9', 'ALT p9 StarterKits');
insert into os_variants values (id_seq.nextval, 'alt.sisyphus', 'ALT regular');
insert into os_variants values (id_seq.nextval, 'alt10.0', 'ALT 10.0');
insert into os_variants values (id_seq.nextval, 'alt10.1', 'ALT 10.1');
insert into os_variants values (id_seq.nextval, 'alt10.2', 'ALT 10.2');
insert into os_variants values (id_seq.nextval, 'alt10.3', 'ALT 10.3');
insert into os_variants values (id_seq.nextval, 'alt8.0', 'ALT 8 Education');
insert into os_variants values (id_seq.nextval, 'alt8.1', 'ALT 8.1');
insert into os_variants values (id_seq.nextval, 'alt8.2', 'ALT 8.2');
insert into os_variants values (id_seq.nextval, 'alt9.0', 'ALT 9.0');
insert into os_variants values (id_seq.nextval, 'alt9.1', 'ALT 9.1');
insert into os_variants values (id_seq.nextval, 'alt9.2', 'ALT 9.2');
insert into os_variants values (id_seq.nextval, 'altlinux1.0', 'Mandrake RE Spring 2001');
insert into os_variants values (id_seq.nextval, 'altlinux2.0', 'ALT Linux 2.0');
insert into os_variants values (id_seq.nextval, 'altlinux2.2', 'ALT Linux 2.2');
insert into os_variants values (id_seq.nextval, 'altlinux2.4', 'ALT Linux 2.4');
insert into os_variants values (id_seq.nextval, 'altlinux3.0', 'ALT Linux 3.0');
insert into os_variants values (id_seq.nextval, 'altlinux4.0', 'ALT Linux 4.0');
insert into os_variants values (id_seq.nextval, 'altlinux4.1', 'ALT Linux 4.1');
insert into os_variants values (id_seq.nextval, 'altlinux5.0', 'ALT Linux 5.0');
insert into os_variants values (id_seq.nextval, 'altlinux6.0', 'ALT Linux 6.0');
insert into os_variants values (id_seq.nextval, 'altlinux7.0', 'ALT Linux 7.0');
insert into os_variants values (id_seq.nextval, 'android-x86-8.1', 'Android-x86 8.1');
insert into os_variants values (id_seq.nextval, 'android-x86-9.0', 'Android-x86 9.0');
insert into os_variants values (id_seq.nextval, 'archlinux', 'Arch Linux');
insert into os_variants values (id_seq.nextval, 'asianux-unknown', 'Asianux unknown');
insert into os_variants values (id_seq.nextval, 'asianux4.6', 'Asianux Server 4 SP6');
insert into os_variants values (id_seq.nextval, 'asianux4.7', 'Asianux Server 4 SP7');
insert into os_variants values (id_seq.nextval, 'asianux7.0', 'Asianux Server 7');
insert into os_variants values (id_seq.nextval, 'asianux7.1', 'Asianux Server 7 SP1');
insert into os_variants values (id_seq.nextval, 'asianux7.2', 'Asianux Server 7 SP2');
insert into os_variants values (id_seq.nextval, 'asianux7.3', 'Asianux Server 7 SP3');
insert into os_variants values (id_seq.nextval, 'asianux8.0', 'Asianux Server 8');
insert into os_variants values (id_seq.nextval, 'caasp-unknown', 'SUSE CaaS Platform Unknown');
insert into os_variants values (id_seq.nextval, 'caasp1.0', 'SUSE CaaS Platform 1.0');
insert into os_variants values (id_seq.nextval, 'caasp2.0', 'SUSE CaaS Platform 2.0');
insert into os_variants values (id_seq.nextval, 'caasp3.0', 'SUSE CaaS Platform 3.0');
insert into os_variants values (id_seq.nextval, 'centos-stream8', 'CentOS Stream 8');
insert into os_variants values (id_seq.nextval, 'centos-stream9', 'CentOS Stream 9');
insert into os_variants values (id_seq.nextval, 'centos5.0', 'CentOS 5.0');
insert into os_variants values (id_seq.nextval, 'centos5.1', 'CentOS 5.1');
insert into os_variants values (id_seq.nextval, 'centos5.10', 'CentOS 5.10');
insert into os_variants values (id_seq.nextval, 'centos5.11', 'CentOS 5.11');
insert into os_variants values (id_seq.nextval, 'centos5.2', 'CentOS 5.2');
insert into os_variants values (id_seq.nextval, 'centos5.3', 'CentOS 5.3');
insert into os_variants values (id_seq.nextval, 'centos5.4', 'CentOS 5.4');
insert into os_variants values (id_seq.nextval, 'centos5.5', 'CentOS 5.5');
insert into os_variants values (id_seq.nextval, 'centos5.6', 'CentOS 5.6');
insert into os_variants values (id_seq.nextval, 'centos5.7', 'CentOS 5.7');
insert into os_variants values (id_seq.nextval, 'centos5.8', 'CentOS 5.8');
insert into os_variants values (id_seq.nextval, 'centos5.9', 'CentOS 5.9');
insert into os_variants values (id_seq.nextval, 'centos6.0', 'CentOS 6.0');
insert into os_variants values (id_seq.nextval, 'centos6.1', 'CentOS 6.1');
insert into os_variants values (id_seq.nextval, 'centos6.10', 'CentOS 6.10');
insert into os_variants values (id_seq.nextval, 'centos6.2', 'CentOS 6.2');
insert into os_variants values (id_seq.nextval, 'centos6.3', 'CentOS 6.3');
insert into os_variants values (id_seq.nextval, 'centos6.4', 'CentOS 6.4');
insert into os_variants values (id_seq.nextval, 'centos6.5', 'CentOS 6.5');
insert into os_variants values (id_seq.nextval, 'centos6.6', 'CentOS 6.6');
insert into os_variants values (id_seq.nextval, 'centos6.7', 'CentOS 6.7');
insert into os_variants values (id_seq.nextval, 'centos6.8', 'CentOS 6.8');
insert into os_variants values (id_seq.nextval, 'centos6.9', 'CentOS 6.9');
insert into os_variants values (id_seq.nextval, 'centos7.0', 'CentOS 7');
insert into os_variants values (id_seq.nextval, 'centos8', 'CentOS 8');
insert into os_variants values (id_seq.nextval, 'circle-unknown', 'Circle Linux Unknown');
insert into os_variants values (id_seq.nextval, 'circle8-unknown', 'Circle Linux 8 Unknown');
insert into os_variants values (id_seq.nextval, 'circle8.4', 'Circle Linux 8.4');
insert into os_variants values (id_seq.nextval, 'circle8.5', 'Circle Linux 8.5');
insert into os_variants values (id_seq.nextval, 'circle9-unknown', 'Circle Linux 9 Unknown');
insert into os_variants values (id_seq.nextval, 'circle9.0', 'Circle Linux 9.0');
insert into os_variants values (id_seq.nextval, 'cirros0.3.0', 'CirrOS 0.3.0');
insert into os_variants values (id_seq.nextval, 'cirros0.3.1', 'CirrOS 0.3.1');
insert into os_variants values (id_seq.nextval, 'cirros0.3.2', 'CirrOS 0.3.2');
insert into os_variants values (id_seq.nextval, 'cirros0.3.3', 'CirrOS 0.3.3');
insert into os_variants values (id_seq.nextval, 'cirros0.3.4', 'CirrOS 0.3.4');
insert into os_variants values (id_seq.nextval, 'cirros0.3.5', 'CirrOS 0.3.5');
insert into os_variants values (id_seq.nextval, 'cirros0.4.0', 'CirrOS 0.4.0');
insert into os_variants values (id_seq.nextval, 'cirros0.5.0', 'CirrOS 0.5.0');
insert into os_variants values (id_seq.nextval, 'cirros0.5.1', 'CirrOS 0.5.1');
insert into os_variants values (id_seq.nextval, 'cirros0.5.2', 'CirrOS 0.5.2');
insert into os_variants values (id_seq.nextval, 'clearlinux', 'Clear Linux OS');
insert into os_variants values (id_seq.nextval, 'debian1.1', 'Debian GNU/Linux 1.1');
insert into os_variants values (id_seq.nextval, 'debian1.2', 'Debian GNU/Linux 1.2');
insert into os_variants values (id_seq.nextval, 'debian1.3', 'Debian GNU/Linux 1.3');
insert into os_variants values (id_seq.nextval, 'debian10', 'Debian 10');
insert into os_variants values (id_seq.nextval, 'debian11', 'Debian 11');
insert into os_variants values (id_seq.nextval, 'debian12', 'Debian 12');
insert into os_variants values (id_seq.nextval, 'debian2.0', 'Debian GNU/Linux 2.0');
insert into os_variants values (id_seq.nextval, 'debian2.1', 'Debian GNU/Linux 2.1');
insert into os_variants values (id_seq.nextval, 'debian2.2', 'Debian GNU/Linux 2.2');
insert into os_variants values (id_seq.nextval, 'debian3', 'Debian GNU/Linux 3.0');
insert into os_variants values (id_seq.nextval, 'debian3.1', 'Debian GNU/Linux 3.1');
insert into os_variants values (id_seq.nextval, 'debian4', 'Debian GNU/Linux 4.0');
insert into os_variants values (id_seq.nextval, 'debian5', 'Debian GNU/Linux 5.0');
insert into os_variants values (id_seq.nextval, 'debian6', 'Debian 6.0');
insert into os_variants values (id_seq.nextval, 'debian7', 'Debian 7');
insert into os_variants values (id_seq.nextval, 'debian8', 'Debian 8');
insert into os_variants values (id_seq.nextval, 'debian9', 'Debian 9');
insert into os_variants values (id_seq.nextval, 'debiantesting', 'Debian testing');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.0', 'DragonFlyBSD 1.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.0A', 'DragonFlyBSD 1.0A');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.10.0', 'DragonFlyBSD 1.10.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.10.1', 'DragonFlyBSD 1.10.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.12.0', 'DragonFlyBSD 1.12.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.12.1', 'DragonFlyBSD 1.12.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.12.2', 'DragonFlyBSD 1.12.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.2.0', 'DragonFlyBSD 1.2.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.2.1', 'DragonFlyBSD 1.2.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.2.2', 'DragonFlyBSD 1.2.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.2.3', 'DragonFlyBSD 1.2.3');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.2.4', 'DragonFlyBSD 1.2.4');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.2.5', 'DragonFlyBSD 1.2.5');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.2.6', 'DragonFlyBSD 1.2.6');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.4.0', 'DragonFlyBSD 1.4.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.4.4', 'DragonFlyBSD 1.4.4');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.6.0', 'DragonFlyBSD 1.6.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.8.0', 'DragonFlyBSD 1.8.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd1.8.1', 'DragonFlyBSD 1.8.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.0.0', 'DragonFlyBSD 2.0.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.0.1', 'DragonFlyBSD 2.0.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.10.1', 'DragonFlyBSD 2.10.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.2.0', 'DragonFlyBSD 2.2.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.2.1', 'DragonFlyBSD 2.2.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.4.0', 'DragonFlyBSD 2.4.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.4.1', 'DragonFlyBSD 2.4.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.6.1', 'DragonFlyBSD 2.6.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.6.2', 'DragonFlyBSD 2.6.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.6.3', 'DragonFlyBSD 2.6.3');
insert into os_variants values (id_seq.nextval, 'dragonflybsd2.8.2', 'DragonFlyBSD 2.8.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.0.1', 'DragonFlyBSD 3.0.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.2.1', 'DragonFlyBSD 3.2.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.4.1', 'DragonFlyBSD 3.4.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.4.2', 'DragonFlyBSD 3.4.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.4.3', 'DragonFlyBSD 3.4.3');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.6.0', 'DragonFlyBSD 3.6.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.6.1', 'DragonFlyBSD 3.6.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.6.2', 'DragonFlyBSD 3.6.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.8.0', 'DragonFlyBSD 3.8.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.8.1', 'DragonFlyBSD 3.8.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd3.8.2', 'DragonFlyBSD 3.8.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.0.0', 'DragonFlyBSD 4.0.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.0.1', 'DragonFlyBSD 4.0.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.2.0', 'DragonFlyBSD 4.2.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.2.1', 'DragonFlyBSD 4.2.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.2.3', 'DragonFlyBSD 4.2.3');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.2.4', 'DragonFlyBSD 4.2.4');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.4.1', 'DragonFlyBSD 4.4.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.4.2', 'DragonFlyBSD 4.4.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.4.3', 'DragonFlyBSD 4.4.3');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.6.0', 'DragonFlyBSD 4.6.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.6.1', 'DragonFlyBSD 4.6.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.6.2', 'DragonFlyBSD 4.6.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.8.0', 'DragonFlyBSD 4.8.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd4.8.1', 'DragonFlyBSD 4.8.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.0.0', 'DragonFlyBSD 5.0.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.0.1', 'DragonFlyBSD 5.0.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.0.2', 'DragonFlyBSD 5.0.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.2.0', 'DragonFlyBSD 5.2.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.2.1', 'DragonFlyBSD 5.2.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.2.2', 'DragonFlyBSD 5.2.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.4.0', 'DragonFlyBSD 5.4.0');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.4.1', 'DragonFlyBSD 5.4.1');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.4.2', 'DragonFlyBSD 5.4.2');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.4.3', 'DragonFlyBSD 5.4.3');
insert into os_variants values (id_seq.nextval, 'dragonflybsd5.6', 'DragonFlyBSD 5.6');
insert into os_variants values (id_seq.nextval, 'elementary5.0', 'Elementary OS 5.0 Juno');
insert into os_variants values (id_seq.nextval, 'eos3.1', 'Endless OS 3.1');
insert into os_variants values (id_seq.nextval, 'eos3.10', 'Endless OS 3.10');
insert into os_variants values (id_seq.nextval, 'eos3.2', 'Endless OS 3.2');
insert into os_variants values (id_seq.nextval, 'eos3.3', 'Endless OS 3.3');
insert into os_variants values (id_seq.nextval, 'eos3.4', 'Endless OS 3.4');
insert into os_variants values (id_seq.nextval, 'eos3.5', 'Endless OS 3.5');
insert into os_variants values (id_seq.nextval, 'eos3.6', 'Endless OS 3.6');
insert into os_variants values (id_seq.nextval, 'eos3.7', 'Endless OS 3.7');
insert into os_variants values (id_seq.nextval, 'eos3.8', 'Endless OS 3.8');
insert into os_variants values (id_seq.nextval, 'eos3.9', 'Endless OS 3.9');
insert into os_variants values (id_seq.nextval, 'eos4.0', 'Endless OS 4.0');
insert into os_variants values (id_seq.nextval, 'eos5.0', 'Endless OS 5.0');
insert into os_variants values (id_seq.nextval, 'eos5.1', 'Endless OS 5.1');
insert into os_variants values (id_seq.nextval, 'eos6.0', 'Endless OS 6.0');
insert into os_variants values (id_seq.nextval, 'eurolinux8', 'EuroLinux 8');
insert into os_variants values (id_seq.nextval, 'eurolinux9', 'EuroLinux 9');
insert into os_variants values (id_seq.nextval, 'fedora-coreos-next', 'Fedora CoreOS');
insert into os_variants values (id_seq.nextval, 'fedora-coreos-stable', 'Fedora CoreOS');
insert into os_variants values (id_seq.nextval, 'fedora-coreos-testing', 'Fedora CoreOS');
insert into os_variants values (id_seq.nextval, 'fedora-eln', 'Fedora ELN');
insert into os_variants values (id_seq.nextval, 'fedora-rawhide', 'Fedora Rawhide');
insert into os_variants values (id_seq.nextval, 'fedora-unknown', 'Fedora');
insert into os_variants values (id_seq.nextval, 'fedora1', 'Fedora Core 1');
insert into os_variants values (id_seq.nextval, 'fedora10', 'Fedora 10');
insert into os_variants values (id_seq.nextval, 'fedora11', 'Fedora 11');
insert into os_variants values (id_seq.nextval, 'fedora12', 'Fedora 12');
insert into os_variants values (id_seq.nextval, 'fedora13', 'Fedora 13');
insert into os_variants values (id_seq.nextval, 'fedora14', 'Fedora 14');
insert into os_variants values (id_seq.nextval, 'fedora15', 'Fedora 15');
insert into os_variants values (id_seq.nextval, 'fedora16', 'Fedora 16');
insert into os_variants values (id_seq.nextval, 'fedora17', 'Fedora 17');
insert into os_variants values (id_seq.nextval, 'fedora18', 'Fedora 18');
insert into os_variants values (id_seq.nextval, 'fedora19', 'Fedora 19');
insert into os_variants values (id_seq.nextval, 'fedora2', 'Fedora Core 2');
insert into os_variants values (id_seq.nextval, 'fedora20', 'Fedora 20');
insert into os_variants values (id_seq.nextval, 'fedora21', 'Fedora 21');
insert into os_variants values (id_seq.nextval, 'fedora22', 'Fedora 22');
insert into os_variants values (id_seq.nextval, 'fedora23', 'Fedora 23');
insert into os_variants values (id_seq.nextval, 'fedora24', 'Fedora 24');
insert into os_variants values (id_seq.nextval, 'fedora25', 'Fedora 25');
insert into os_variants values (id_seq.nextval, 'fedora26', 'Fedora 26');
insert into os_variants values (id_seq.nextval, 'fedora27', 'Fedora 27');
insert into os_variants values (id_seq.nextval, 'fedora28', 'Fedora 28');
insert into os_variants values (id_seq.nextval, 'fedora29', 'Fedora 29');
insert into os_variants values (id_seq.nextval, 'fedora3', 'Fedora Core 3');
insert into os_variants values (id_seq.nextval, 'fedora30', 'Fedora 30');
insert into os_variants values (id_seq.nextval, 'fedora31', 'Fedora 31');
insert into os_variants values (id_seq.nextval, 'fedora32', 'Fedora 32');
insert into os_variants values (id_seq.nextval, 'fedora33', 'Fedora 33');
insert into os_variants values (id_seq.nextval, 'fedora34', 'Fedora 34');
insert into os_variants values (id_seq.nextval, 'fedora35', 'Fedora 35');
insert into os_variants values (id_seq.nextval, 'fedora36', 'Fedora Linux 36');
insert into os_variants values (id_seq.nextval, 'fedora37', 'Fedora Linux 37');
insert into os_variants values (id_seq.nextval, 'fedora38', 'Fedora Linux 38');
insert into os_variants values (id_seq.nextval, 'fedora39', 'Fedora Linux 39');
insert into os_variants values (id_seq.nextval, 'fedora4', 'Fedora Core 4');
insert into os_variants values (id_seq.nextval, 'fedora40', 'Fedora Linux 40');
insert into os_variants values (id_seq.nextval, 'fedora5', 'Fedora Core 5');
insert into os_variants values (id_seq.nextval, 'fedora6', 'Fedora Core 6');
insert into os_variants values (id_seq.nextval, 'fedora7', 'Fedora 7');
insert into os_variants values (id_seq.nextval, 'fedora8', 'Fedora 8');
insert into os_variants values (id_seq.nextval, 'fedora9', 'Fedora 9');
insert into os_variants values (id_seq.nextval, 'freebsd1.0', 'FreeBSD 1.0');
insert into os_variants values (id_seq.nextval, 'freebsd10.0', 'FreeBSD 10.0');
insert into os_variants values (id_seq.nextval, 'freebsd10.1', 'FreeBSD 10.1');
insert into os_variants values (id_seq.nextval, 'freebsd10.2', 'FreeBSD 10.2');
insert into os_variants values (id_seq.nextval, 'freebsd10.3', 'FreeBSD 10.3');
insert into os_variants values (id_seq.nextval, 'freebsd10.4', 'FreeBSD 10.4');
insert into os_variants values (id_seq.nextval, 'freebsd11.0', 'FreeBSD 11.0');
insert into os_variants values (id_seq.nextval, 'freebsd11.1', 'FreeBSD 11.1');
insert into os_variants values (id_seq.nextval, 'freebsd11.2', 'FreeBSD 11.2');
insert into os_variants values (id_seq.nextval, 'freebsd11.3', 'FreeBSD 11.3');
insert into os_variants values (id_seq.nextval, 'freebsd11.4', 'FreeBSD 11.4');
insert into os_variants values (id_seq.nextval, 'freebsd12.0', 'FreeBSD 12.0');
insert into os_variants values (id_seq.nextval, 'freebsd12.1', 'FreeBSD 12.1');
insert into os_variants values (id_seq.nextval, 'freebsd12.2', 'FreeBSD 12.2');
insert into os_variants values (id_seq.nextval, 'freebsd12.3', 'FreeBSD 12.3');
insert into os_variants values (id_seq.nextval, 'freebsd12.4', 'FreeBSD 12.4');
insert into os_variants values (id_seq.nextval, 'freebsd13.0', 'FreeBSD 13.0');
insert into os_variants values (id_seq.nextval, 'freebsd13.1', 'FreeBSD 13.1');
insert into os_variants values (id_seq.nextval, 'freebsd13.2', 'FreeBSD 13.2');
insert into os_variants values (id_seq.nextval, 'freebsd14.0', 'FreeBSD 14.0');
insert into os_variants values (id_seq.nextval, 'freebsd2.0', 'FreeBSD 2.0');
insert into os_variants values (id_seq.nextval, 'freebsd2.0.5', 'FreeBSD 2.0.5');
insert into os_variants values (id_seq.nextval, 'freebsd2.2.8', 'FreeBSD 2.2.8');
insert into os_variants values (id_seq.nextval, 'freebsd2.2.9', 'FreeBSD 2.2.9');
insert into os_variants values (id_seq.nextval, 'freebsd3.0', 'FreeBSD 3.0');
insert into os_variants values (id_seq.nextval, 'freebsd3.2', 'FreeBSD 3.2');
insert into os_variants values (id_seq.nextval, 'freebsd4.0', 'FreeBSD 4.0');
insert into os_variants values (id_seq.nextval, 'freebsd4.1', 'FreeBSD 4.1');
insert into os_variants values (id_seq.nextval, 'freebsd4.10', 'FreeBSD 4.10');
insert into os_variants values (id_seq.nextval, 'freebsd4.11', 'FreeBSD 4.11');
insert into os_variants values (id_seq.nextval, 'freebsd4.2', 'FreeBSD 4.2');
insert into os_variants values (id_seq.nextval, 'freebsd4.3', 'FreeBSD 4.3');
insert into os_variants values (id_seq.nextval, 'freebsd4.4', 'FreeBSD 4.4');
insert into os_variants values (id_seq.nextval, 'freebsd4.5', 'FreeBSD 4.5');
insert into os_variants values (id_seq.nextval, 'freebsd4.6', 'FreeBSD 4.6');
insert into os_variants values (id_seq.nextval, 'freebsd4.7', 'FreeBSD 4.7');
insert into os_variants values (id_seq.nextval, 'freebsd4.8', 'FreeBSD 4.8');
insert into os_variants values (id_seq.nextval, 'freebsd4.9', 'FreeBSD 4.9');
insert into os_variants values (id_seq.nextval, 'freebsd5.0', 'FreeBSD 5.0');
insert into os_variants values (id_seq.nextval, 'freebsd5.1', 'FreeBSD 5.1');
insert into os_variants values (id_seq.nextval, 'freebsd5.2', 'FreeBSD 5.2');
insert into os_variants values (id_seq.nextval, 'freebsd5.2.1', 'FreeBSD 5.2.1');
insert into os_variants values (id_seq.nextval, 'freebsd5.3', 'FreeBSD 5.3');
insert into os_variants values (id_seq.nextval, 'freebsd5.4', 'FreeBSD 5.4');
insert into os_variants values (id_seq.nextval, 'freebsd5.5', 'FreeBSD 5.5');
insert into os_variants values (id_seq.nextval, 'freebsd6.0', 'FreeBSD 6.0');
insert into os_variants values (id_seq.nextval, 'freebsd6.1', 'FreeBSD 6.1');
insert into os_variants values (id_seq.nextval, 'freebsd6.2', 'FreeBSD 6.2');
insert into os_variants values (id_seq.nextval, 'freebsd6.3', 'FreeBSD 6.3');
insert into os_variants values (id_seq.nextval, 'freebsd6.4', 'FreeBSD 6.4');
insert into os_variants values (id_seq.nextval, 'freebsd7.0', 'FreeBSD 7.0');
insert into os_variants values (id_seq.nextval, 'freebsd7.1', 'FreeBSD 7.1');
insert into os_variants values (id_seq.nextval, 'freebsd7.2', 'FreeBSD 7.2');
insert into os_variants values (id_seq.nextval, 'freebsd7.3', 'FreeBSD 7.3');
insert into os_variants values (id_seq.nextval, 'freebsd7.4', 'FreeBSD 7.4');
insert into os_variants values (id_seq.nextval, 'freebsd8.0', 'FreeBSD 8.0');
insert into os_variants values (id_seq.nextval, 'freebsd8.1', 'FreeBSD 8.1');
insert into os_variants values (id_seq.nextval, 'freebsd8.2', 'FreeBSD 8.2');
insert into os_variants values (id_seq.nextval, 'freebsd8.3', 'FreeBSD 8.3');
insert into os_variants values (id_seq.nextval, 'freebsd8.4', 'FreeBSD 8.4');
insert into os_variants values (id_seq.nextval, 'freebsd9.0', 'FreeBSD 9.0');
insert into os_variants values (id_seq.nextval, 'freebsd9.1', 'FreeBSD 9.1');
insert into os_variants values (id_seq.nextval, 'freebsd9.2', 'FreeBSD 9.2');
insert into os_variants values (id_seq.nextval, 'freebsd9.3', 'FreeBSD 9.3');
insert into os_variants values (id_seq.nextval, 'freedos1.2', 'FreeDOS 1.2');
insert into os_variants values (id_seq.nextval, 'freedos1.3', 'FreeDOS 1.3');
insert into os_variants values (id_seq.nextval, 'freenix14.2', 'Freenix 14.2');
insert into os_variants values (id_seq.nextval, 'gentoo', 'Gentoo Linux');
insert into os_variants values (id_seq.nextval, 'gnome-continuous-3.10', 'GNOME 3.10');
insert into os_variants values (id_seq.nextval, 'gnome-continuous-3.12', 'GNOME 3.12');
insert into os_variants values (id_seq.nextval, 'gnome-continuous-3.14', 'GNOME 3.14');
insert into os_variants values (id_seq.nextval, 'gnome3.6', 'GNOME 3.6');
insert into os_variants values (id_seq.nextval, 'gnome3.8', 'GNOME 3.8');
insert into os_variants values (id_seq.nextval, 'guix-1.1', 'Guix 1.1');
insert into os_variants values (id_seq.nextval, 'guix-1.3', 'Guix 1.3');
insert into os_variants values (id_seq.nextval, 'guix-hurd-latest', 'Guix Hurd Latest');
insert into os_variants values (id_seq.nextval, 'guix-latest', 'Guix latest');
insert into os_variants values (id_seq.nextval, 'haikunightly', 'Haiku Nightly');
insert into os_variants values (id_seq.nextval, 'haikur1alpha1', 'Haiku R1/Alpha1');
insert into os_variants values (id_seq.nextval, 'haikur1alpha2', 'Haiku R1/Alpha2');
insert into os_variants values (id_seq.nextval, 'haikur1alpha3', 'Haiku R1/Alpha3');
insert into os_variants values (id_seq.nextval, 'haikur1alpha4.1', 'Haiku R1/Alpha4.1');
insert into os_variants values (id_seq.nextval, 'haikur1beta1', 'Haiku R1/Beta1');
insert into os_variants values (id_seq.nextval, 'haikur1beta2', 'Haiku R1/Beta2');
insert into os_variants values (id_seq.nextval, 'haikur1beta3', 'Haiku R1/Beta3');
insert into os_variants values (id_seq.nextval, 'haikur1beta4', 'Haiku R1/Beta4');
insert into os_variants values (id_seq.nextval, 'hyperbola03', 'Hyperbola');
insert into os_variants values (id_seq.nextval, 'linux2016', 'Generic Linux 2016');
insert into os_variants values (id_seq.nextval, 'linux2018', 'Generic Linux 2018');
insert into os_variants values (id_seq.nextval, 'linux2020', 'Generic Linux 2020');
insert into os_variants values (id_seq.nextval, 'linux2022', 'Generic Linux 2022');
insert into os_variants values (id_seq.nextval, 'macosx10.0', 'MacOS X Cheetah');
insert into os_variants values (id_seq.nextval, 'macosx10.1', 'MacOS X Puma');
insert into os_variants values (id_seq.nextval, 'macosx10.2', 'MacOS X Jaguar');
insert into os_variants values (id_seq.nextval, 'macosx10.3', 'MacOS X Panther');
insert into os_variants values (id_seq.nextval, 'macosx10.4', 'MacOS X Tiger');
insert into os_variants values (id_seq.nextval, 'macosx10.5', 'MacOS X Leopard');
insert into os_variants values (id_seq.nextval, 'macosx10.6', 'MacOS X Snow Leopard');
insert into os_variants values (id_seq.nextval, 'macosx10.7', 'MacOS X Lion');
insert into os_variants values (id_seq.nextval, 'mageia1', 'Mageia 1');
insert into os_variants values (id_seq.nextval, 'mageia2', 'Mageia 2');
insert into os_variants values (id_seq.nextval, 'mageia3', 'Mageia 3');
insert into os_variants values (id_seq.nextval, 'mageia4', 'Mageia 4');
insert into os_variants values (id_seq.nextval, 'mageia5', 'Mageia 5');
insert into os_variants values (id_seq.nextval, 'mageia6', 'Mageia 6');
insert into os_variants values (id_seq.nextval, 'mageia7', 'Mageia 7');
insert into os_variants values (id_seq.nextval, 'mageia8', 'Mageia 8');
insert into os_variants values (id_seq.nextval, 'mageia9', 'Mageia 9');
insert into os_variants values (id_seq.nextval, 'mandrake10.0', 'Mandrake Linux 10.0');
insert into os_variants values (id_seq.nextval, 'mandrake10.1', 'Mandrake Linux 10.1');
insert into os_variants values (id_seq.nextval, 'mandrake10.2', 'Mandrake Linux 10.2');
insert into os_variants values (id_seq.nextval, 'mandrake5.1', 'Mandrake Linux 5.1');
insert into os_variants values (id_seq.nextval, 'mandrake5.2', 'Mandrake Linux 5.2');
insert into os_variants values (id_seq.nextval, 'mandrake5.3', 'Mandrake Linux 5.3');
insert into os_variants values (id_seq.nextval, 'mandrake6.0', 'Mandrake Linux 6.0');
insert into os_variants values (id_seq.nextval, 'mandrake6.1', 'Mandrake Linux 6.1');
insert into os_variants values (id_seq.nextval, 'mandrake7.0', 'Mandrake Linux 7.0');
insert into os_variants values (id_seq.nextval, 'mandrake7.1', 'Mandrake Linux 7.1');
insert into os_variants values (id_seq.nextval, 'mandrake7.2', 'Mandrake Linux 7.2');
insert into os_variants values (id_seq.nextval, 'mandrake8.0', 'Mandrake Linux 8.0');
insert into os_variants values (id_seq.nextval, 'mandrake8.1', 'Mandrake Linux 8.1');
insert into os_variants values (id_seq.nextval, 'mandrake8.2', 'Mandrake Linux 8.2');
insert into os_variants values (id_seq.nextval, 'mandrake9.0', 'Mandrake Linux 9.0');
insert into os_variants values (id_seq.nextval, 'mandrake9.1', 'Mandrake Linux 9.1');
insert into os_variants values (id_seq.nextval, 'mandrake9.2', 'Mandrake Linux 9.2');
insert into os_variants values (id_seq.nextval, 'mandriva2006.0', 'Mandriva Linux 2006.0');
insert into os_variants values (id_seq.nextval, 'mandriva2007', 'Mandriva Linux 2007');
insert into os_variants values (id_seq.nextval, 'mandriva2007.1', 'Mandriva Linux 2007 Spring');
insert into os_variants values (id_seq.nextval, 'mandriva2008.0', 'Mandriva Linux 2008');
insert into os_variants values (id_seq.nextval, 'mandriva2008.1', 'Mandriva Linux 2008 Spring');
insert into os_variants values (id_seq.nextval, 'mandriva2009.0', 'Mandriva Linux 2009');
insert into os_variants values (id_seq.nextval, 'mandriva2009.1', 'Mandriva Linux 2009 Spring');
insert into os_variants values (id_seq.nextval, 'mandriva2010.0', 'Mandriva Linux 2010');
insert into os_variants values (id_seq.nextval, 'mandriva2010.1', 'Mandriva Linux 2010 Spring');
insert into os_variants values (id_seq.nextval, 'mandriva2010.2', 'Mandriva Linux 2010.2');
insert into os_variants values (id_seq.nextval, 'mandriva2011', 'Mandriva Linux 2011');
insert into os_variants values (id_seq.nextval, 'manjaro', 'Manjaro');
insert into os_variants values (id_seq.nextval, 'mbs1.0', 'Mandriva Business Server 1.0');
insert into os_variants values (id_seq.nextval, 'mes5', 'Mandriva Enterprise Server 5.0');
insert into os_variants values (id_seq.nextval, 'mes5.1', 'Mandriva Enterprise Server 5.1');
insert into os_variants values (id_seq.nextval, 'miraclelinux8-unknown', 'MIRACLE LINUX 8 Unknown');
insert into os_variants values (id_seq.nextval, 'miraclelinux8.4', 'MIRACLE LINUX 8.4');
insert into os_variants values (id_seq.nextval, 'miraclelinux9-unknown', 'MIRACLE LINUX 9 Unknown');
insert into os_variants values (id_seq.nextval, 'miraclelinux9.0', 'MIRACLE LINUX 9.0');
insert into os_variants values (id_seq.nextval, 'msdos6.22', 'Microsoft MS-DOS 6.22');
insert into os_variants values (id_seq.nextval, 'netbsd0.8', 'NetBSD 0.8');
insert into os_variants values (id_seq.nextval, 'netbsd0.9', 'NetBSD 0.9');
insert into os_variants values (id_seq.nextval, 'netbsd1.0', 'NetBSD 1.0');
insert into os_variants values (id_seq.nextval, 'netbsd1.1', 'NetBSD 1.1');
insert into os_variants values (id_seq.nextval, 'netbsd1.2', 'NetBSD 1.2');
insert into os_variants values (id_seq.nextval, 'netbsd1.3', 'NetBSD 1.3');
insert into os_variants values (id_seq.nextval, 'netbsd1.4', 'NetBSD 1.4');
insert into os_variants values (id_seq.nextval, 'netbsd1.5', 'NetBSD 1.5');
insert into os_variants values (id_seq.nextval, 'netbsd1.6', 'NetBSD 1.6');
insert into os_variants values (id_seq.nextval, 'netbsd10.0', 'NetBSD 10.0');
insert into os_variants values (id_seq.nextval, 'netbsd2.0', 'NetBSD 2.0');
insert into os_variants values (id_seq.nextval, 'netbsd3.0', 'NetBSD 3.0');
insert into os_variants values (id_seq.nextval, 'netbsd4.0', 'NetBSD 4.0');
insert into os_variants values (id_seq.nextval, 'netbsd5.0', 'NetBSD 5.0');
insert into os_variants values (id_seq.nextval, 'netbsd5.1', 'NetBSD 5.1');
insert into os_variants values (id_seq.nextval, 'netbsd6.0', 'NetBSD 6.0');
insert into os_variants values (id_seq.nextval, 'netbsd6.1', 'NetBSD 6.1');
insert into os_variants values (id_seq.nextval, 'netbsd7.0', 'NetBSD 7.0');
insert into os_variants values (id_seq.nextval, 'netbsd7.1', 'NetBSD 7.1');
insert into os_variants values (id_seq.nextval, 'netbsd7.1.1', 'NetBSD 7.1.1');
insert into os_variants values (id_seq.nextval, 'netbsd7.1.2', 'NetBSD 7.1.2');
insert into os_variants values (id_seq.nextval, 'netbsd7.2', 'NetBSD 7.2');
insert into os_variants values (id_seq.nextval, 'netbsd8.0', 'NetBSD 8.0');
insert into os_variants values (id_seq.nextval, 'netbsd8.1', 'NetBSD 8.1');
insert into os_variants values (id_seq.nextval, 'netbsd8.2', 'NetBSD 8.2');
insert into os_variants values (id_seq.nextval, 'netbsd9.0', 'NetBSD 9.0');
insert into os_variants values (id_seq.nextval, 'netbsd9.1', 'NetBSD 9.1');
insert into os_variants values (id_seq.nextval, 'netbsd9.2', 'NetBSD 9.2');
insert into os_variants values (id_seq.nextval, 'netbsd9.3', 'NetBSD 9.3');
insert into os_variants values (id_seq.nextval, 'netbsd9.4', 'NetBSD 9.4');
insert into os_variants values (id_seq.nextval, 'netware4', 'Novell Netware 4');
insert into os_variants values (id_seq.nextval, 'netware5', 'Novell Netware 5');
insert into os_variants values (id_seq.nextval, 'netware6', 'Novell Netware 6');
insert into os_variants values (id_seq.nextval, 'nixos-20.03', 'NixOS 20.03');
insert into os_variants values (id_seq.nextval, 'nixos-20.09', 'NixOS 20.09');
insert into os_variants values (id_seq.nextval, 'nixos-21.05', 'NixOS 21.05');
insert into os_variants values (id_seq.nextval, 'nixos-21.11', 'NixOS 21.11');
insert into os_variants values (id_seq.nextval, 'nixos-22.05', 'NixOS 22.05');
insert into os_variants values (id_seq.nextval, 'nixos-22.11', 'NixOS 22.11');
insert into os_variants values (id_seq.nextval, 'nixos-23.05', 'NixOS 23.05');
insert into os_variants values (id_seq.nextval, 'nixos-23.11', 'NixOS 23.11');
insert into os_variants values (id_seq.nextval, 'nixos-24.05', 'NixOS 24.05');
insert into os_variants values (id_seq.nextval, 'nixos-unknown', 'NixOS');
insert into os_variants values (id_seq.nextval, 'nixos-unstable', 'NixOS Unstable');
insert into os_variants values (id_seq.nextval, 'oel4.4', 'Oracle Enterprise Linux 4.4');
insert into os_variants values (id_seq.nextval, 'oel4.5', 'Oracle Enterprise Linux 4.5');
insert into os_variants values (id_seq.nextval, 'oel4.6', 'Oracle Enterprise Linux 4.6');
insert into os_variants values (id_seq.nextval, 'oel4.7', 'Oracle Enterprise Linux 4.7');
insert into os_variants values (id_seq.nextval, 'oel4.8', 'Oracle Enterprise Linux 4.8');
insert into os_variants values (id_seq.nextval, 'oel4.9', 'Oracle Enterprise Linux 4.9');
insert into os_variants values (id_seq.nextval, 'oel5.0', 'Oracle Enterprise Linux 5.0');
insert into os_variants values (id_seq.nextval, 'oel5.1', 'Oracle Enterprise Linux 5.1');
insert into os_variants values (id_seq.nextval, 'oel5.2', 'Oracle Enterprise Linux 5.2');
insert into os_variants values (id_seq.nextval, 'oel5.3', 'Oracle Enterprise Linux 5.3');
insert into os_variants values (id_seq.nextval, 'oel5.4', 'Oracle Enterprise Linux 5.4');
insert into os_variants values (id_seq.nextval, 'ol5.10', 'Oracle Linux 5.10');
insert into os_variants values (id_seq.nextval, 'ol5.11', 'Oracle Linux 5.11');
insert into os_variants values (id_seq.nextval, 'ol5.5', 'Oracle Linux 5.5');
insert into os_variants values (id_seq.nextval, 'ol5.6', 'Oracle Linux 5.6');
insert into os_variants values (id_seq.nextval, 'ol5.7', 'Oracle Linux 5.7');
insert into os_variants values (id_seq.nextval, 'ol5.8', 'Oracle Linux 5.8');
insert into os_variants values (id_seq.nextval, 'ol5.9', 'Oracle Linux 5.9');
insert into os_variants values (id_seq.nextval, 'ol6.0', 'Oracle Linux 6.0');
insert into os_variants values (id_seq.nextval, 'ol6.1', 'Oracle Linux 6.1');
insert into os_variants values (id_seq.nextval, 'ol6.10', 'Oracle Linux 6.10');
insert into os_variants values (id_seq.nextval, 'ol6.2', 'Oracle Linux 6.2');
insert into os_variants values (id_seq.nextval, 'ol6.3', 'Oracle Linux 6.3');
insert into os_variants values (id_seq.nextval, 'ol6.4', 'Oracle Linux 6.4');
insert into os_variants values (id_seq.nextval, 'ol6.5', 'Oracle Linux 6.5');
insert into os_variants values (id_seq.nextval, 'ol6.6', 'Oracle Linux 6.6');
insert into os_variants values (id_seq.nextval, 'ol6.7', 'Oracle Linux 6.7');
insert into os_variants values (id_seq.nextval, 'ol6.8', 'Oracle Linux 6.8');
insert into os_variants values (id_seq.nextval, 'ol6.9', 'Oracle Linux 6.9');
insert into os_variants values (id_seq.nextval, 'ol7.0', 'Oracle Linux 7.0');
insert into os_variants values (id_seq.nextval, 'ol7.1', 'Oracle Linux 7.1');
insert into os_variants values (id_seq.nextval, 'ol7.2', 'Oracle Linux 7.2');
insert into os_variants values (id_seq.nextval, 'ol7.3', 'Oracle Linux 7.3');
insert into os_variants values (id_seq.nextval, 'ol7.4', 'Oracle Linux 7.4');
insert into os_variants values (id_seq.nextval, 'ol7.5', 'Oracle Linux 7.5');
insert into os_variants values (id_seq.nextval, 'ol7.6', 'Oracle Linux 7.6');
insert into os_variants values (id_seq.nextval, 'ol7.7', 'Oracle Linux 7.7');
insert into os_variants values (id_seq.nextval, 'ol7.8', 'Oracle Linux 7.8');
insert into os_variants values (id_seq.nextval, 'ol7.9', 'Oracle Linux 7.9');
insert into os_variants values (id_seq.nextval, 'ol8.0', 'Oracle Linux 8.0');
insert into os_variants values (id_seq.nextval, 'ol8.1', 'Oracle Linux 8.1');
insert into os_variants values (id_seq.nextval, 'ol8.10', 'Oracle Linux 8.10');
insert into os_variants values (id_seq.nextval, 'ol8.2', 'Oracle Linux 8.2');
insert into os_variants values (id_seq.nextval, 'ol8.3', 'Oracle Linux 8.3');
insert into os_variants values (id_seq.nextval, 'ol8.4', 'Oracle Linux 8.4');
insert into os_variants values (id_seq.nextval, 'ol8.5', 'Oracle Linux 8.5');
insert into os_variants values (id_seq.nextval, 'ol8.6', 'Oracle Linux 8.6');
insert into os_variants values (id_seq.nextval, 'ol8.7', 'Oracle Linux 8.7');
insert into os_variants values (id_seq.nextval, 'ol8.8', 'Oracle Linux 8.8');
insert into os_variants values (id_seq.nextval, 'ol8.9', 'Oracle Linux 8.9');
insert into os_variants values (id_seq.nextval, 'ol9-unknown', 'Oracle Linux 9 Unknown');
insert into os_variants values (id_seq.nextval, 'ol9.0', 'Oracle Linux 9.0');
insert into os_variants values (id_seq.nextval, 'ol9.1', 'Oracle Linux 9.1');
insert into os_variants values (id_seq.nextval, 'ol9.2', 'Oracle Linux 9.2');
insert into os_variants values (id_seq.nextval, 'ol9.3', 'Oracle Linux 9.3');
insert into os_variants values (id_seq.nextval, 'ol9.4', 'Oracle Linux 9.4');
insert into os_variants values (id_seq.nextval, 'omnios', 'OmniOSCE Bloody');
insert into os_variants values (id_seq.nextval, 'openbsd4.2', 'OpenBSD 4.2');
insert into os_variants values (id_seq.nextval, 'openbsd4.3', 'OpenBSD 4.3');
insert into os_variants values (id_seq.nextval, 'openbsd4.4', 'OpenBSD 4.4');
insert into os_variants values (id_seq.nextval, 'openbsd4.5', 'OpenBSD 4.5');
insert into os_variants values (id_seq.nextval, 'openbsd4.8', 'OpenBSD 4.8');
insert into os_variants values (id_seq.nextval, 'openbsd4.9', 'OpenBSD 4.9');
insert into os_variants values (id_seq.nextval, 'openbsd5.0', 'OpenBSD 5.0');
insert into os_variants values (id_seq.nextval, 'openbsd5.1', 'OpenBSD 5.1');
insert into os_variants values (id_seq.nextval, 'openbsd5.2', 'OpenBSD 5.2');
insert into os_variants values (id_seq.nextval, 'openbsd5.3', 'OpenBSD 5.3');
insert into os_variants values (id_seq.nextval, 'openbsd5.4', 'OpenBSD 5.4');
insert into os_variants values (id_seq.nextval, 'openbsd5.5', 'OpenBSD 5.5');
insert into os_variants values (id_seq.nextval, 'openbsd5.6', 'OpenBSD 5.6');
insert into os_variants values (id_seq.nextval, 'openbsd5.7', 'OpenBSD 5.7');
insert into os_variants values (id_seq.nextval, 'openbsd5.8', 'OpenBSD 5.8');
insert into os_variants values (id_seq.nextval, 'openbsd5.9', 'OpenBSD 5.9');
insert into os_variants values (id_seq.nextval, 'openbsd6.0', 'OpenBSD 6.0');
insert into os_variants values (id_seq.nextval, 'openbsd6.1', 'OpenBSD 6.1');
insert into os_variants values (id_seq.nextval, 'openbsd6.2', 'OpenBSD 6.2');
insert into os_variants values (id_seq.nextval, 'openbsd6.3', 'OpenBSD 6.3');
insert into os_variants values (id_seq.nextval, 'openbsd6.4', 'OpenBSD 6.4');
insert into os_variants values (id_seq.nextval, 'openbsd6.5', 'OpenBSD 6.5');
insert into os_variants values (id_seq.nextval, 'openbsd6.6', 'OpenBSD 6.6');
insert into os_variants values (id_seq.nextval, 'openbsd6.7', 'OpenBSD 6.7');
insert into os_variants values (id_seq.nextval, 'openbsd6.8', 'OpenBSD 6.8');
insert into os_variants values (id_seq.nextval, 'openbsd6.9', 'OpenBSD 6.9');
insert into os_variants values (id_seq.nextval, 'openbsd7.0', 'OpenBSD 7.0');
insert into os_variants values (id_seq.nextval, 'openbsd7.1', 'OpenBSD 7.1');
insert into os_variants values (id_seq.nextval, 'openbsd7.2', 'OpenBSD 7.2');
insert into os_variants values (id_seq.nextval, 'openbsd7.3', 'OpenBSD 7.3');
insert into os_variants values (id_seq.nextval, 'openbsd7.4', 'OpenBSD 7.4');
insert into os_variants values (id_seq.nextval, 'openbsd7.5', 'OpenBSD 7.5');
insert into os_variants values (id_seq.nextval, 'openindiana', 'OpenIndiana Hipster');
insert into os_variants values (id_seq.nextval, 'opensolaris2009.06', 'OpenSolaris 2009.06');
insert into os_variants values (id_seq.nextval, 'opensuse-factory', 'openSUSE');
insert into os_variants values (id_seq.nextval, 'opensuse-unknown', 'openSUSE');
insert into os_variants values (id_seq.nextval, 'opensuse10.2', 'openSUSE 10.2');
insert into os_variants values (id_seq.nextval, 'opensuse10.3', 'openSUSE 10.3');
insert into os_variants values (id_seq.nextval, 'opensuse11.0', 'openSUSE 11.0');
insert into os_variants values (id_seq.nextval, 'opensuse11.1', 'openSUSE 11.1');
insert into os_variants values (id_seq.nextval, 'opensuse11.2', 'openSUSE 11.2');
insert into os_variants values (id_seq.nextval, 'opensuse11.3', 'openSUSE 11.3');
insert into os_variants values (id_seq.nextval, 'opensuse11.4', 'openSUSE 11.4');
insert into os_variants values (id_seq.nextval, 'opensuse12.1', 'openSUSE 12.1');
insert into os_variants values (id_seq.nextval, 'opensuse12.2', 'openSUSE 12.2');
insert into os_variants values (id_seq.nextval, 'opensuse12.3', 'openSUSE 12.3');
insert into os_variants values (id_seq.nextval, 'opensuse13.1', 'openSUSE 13.1');
insert into os_variants values (id_seq.nextval, 'opensuse13.2', 'openSUSE 13.2');
insert into os_variants values (id_seq.nextval, 'opensuse15.0', 'openSUSE Leap 15.0');
insert into os_variants values (id_seq.nextval, 'opensuse15.1', 'openSUSE Leap 15.1');
insert into os_variants values (id_seq.nextval, 'opensuse15.2', 'openSUSE Leap 15.2');
insert into os_variants values (id_seq.nextval, 'opensuse15.3', 'openSUSE Leap 15.3');
insert into os_variants values (id_seq.nextval, 'opensuse15.4', 'openSUSE Leap 15.4');
insert into os_variants values (id_seq.nextval, 'opensuse15.5', 'openSUSE Leap 15.5');
insert into os_variants values (id_seq.nextval, 'opensuse42.1', 'openSUSE Leap 42.1');
insert into os_variants values (id_seq.nextval, 'opensuse42.2', 'openSUSE Leap 42.2');
insert into os_variants values (id_seq.nextval, 'opensuse42.3', 'openSUSE Leap 42.3');
insert into os_variants values (id_seq.nextval, 'opensusetumbleweed', 'openSUSE Tumbleweed');
insert into os_variants values (id_seq.nextval, 'popos17.10', 'Pop!_OS 17.10');
insert into os_variants values (id_seq.nextval, 'popos18.04', 'Pop!_OS 18.04');
insert into os_variants values (id_seq.nextval, 'popos18.10', 'Pop!_OS 18.10');
insert into os_variants values (id_seq.nextval, 'popos19.04', 'Pop!_OS 19.04');
insert into os_variants values (id_seq.nextval, 'popos19.10', 'Pop!_OS 19.10');
insert into os_variants values (id_seq.nextval, 'popos20.04', 'Pop!_OS 20.04');
insert into os_variants values (id_seq.nextval, 'popos20.10', 'Pop!_OS 20.10');
insert into os_variants values (id_seq.nextval, 'pureos10', 'PureOS');
insert into os_variants values (id_seq.nextval, 'pureos8', 'PureOS');
insert into os_variants values (id_seq.nextval, 'pureos9', 'PureOS');
insert into os_variants values (id_seq.nextval, 'rhel-atomic-7.0', 'Red Hat Enterprise Linux Atomic Host 7.0');
insert into os_variants values (id_seq.nextval, 'rhel-atomic-7.1', 'Red Hat Enterprise Linux Atomic Host 7.1');
insert into os_variants values (id_seq.nextval, 'rhel-atomic-7.2', 'Red Hat Enterprise Linux Atomic Host 7.2');
insert into os_variants values (id_seq.nextval, 'rhel-atomic-7.3', 'Red Hat Enterprise Linux Atomic Host 7.3');
insert into os_variants values (id_seq.nextval, 'rhel-atomic-7.4', 'Red Hat Enterprise Linux Atomic Host 7.4');
insert into os_variants values (id_seq.nextval, 'rhel-unknown', 'Red Hat Enterprise Linux Unknown');
insert into os_variants values (id_seq.nextval, 'rhel2.1', 'Red Hat Enterprise Linux 2.1');
insert into os_variants values (id_seq.nextval, 'rhel2.1.1', 'Red Hat Enterprise Linux 2.1 Update 1');
insert into os_variants values (id_seq.nextval, 'rhel2.1.2', 'Red Hat Enterprise Linux 2.1 Update 2');
insert into os_variants values (id_seq.nextval, 'rhel2.1.3', 'Red Hat Enterprise Linux 2.1 Update 3');
insert into os_variants values (id_seq.nextval, 'rhel2.1.4', 'Red Hat Enterprise Linux 2.1 Update 4');
insert into os_variants values (id_seq.nextval, 'rhel2.1.5', 'Red Hat Enterprise Linux 2.1 Update 5');
insert into os_variants values (id_seq.nextval, 'rhel2.1.6', 'Red Hat Enterprise Linux 2.1 Update 6');
insert into os_variants values (id_seq.nextval, 'rhel2.1.7', 'Red Hat Enterprise Linux 2.1 Update 7');
insert into os_variants values (id_seq.nextval, 'rhel3', 'Red Hat Enterprise Linux 3');
insert into os_variants values (id_seq.nextval, 'rhel3.1', 'Red Hat Enterprise Linux 3 Update 1');
insert into os_variants values (id_seq.nextval, 'rhel3.2', 'Red Hat Enterprise Linux 3 Update 2');
insert into os_variants values (id_seq.nextval, 'rhel3.3', 'Red Hat Enterprise Linux 3 Update 3');
insert into os_variants values (id_seq.nextval, 'rhel3.4', 'Red Hat Enterprise Linux 3 Update 4');
insert into os_variants values (id_seq.nextval, 'rhel3.5', 'Red Hat Enterprise Linux 3 Update 5');
insert into os_variants values (id_seq.nextval, 'rhel3.6', 'Red Hat Enterprise Linux 3 Update 6');
insert into os_variants values (id_seq.nextval, 'rhel3.7', 'Red Hat Enterprise Linux 3 Update 7');
insert into os_variants values (id_seq.nextval, 'rhel3.8', 'Red Hat Enterprise Linux 3 Update 8');
insert into os_variants values (id_seq.nextval, 'rhel3.9', 'Red Hat Enterprise Linux 3 Update 9');
insert into os_variants values (id_seq.nextval, 'rhel4.0', 'Red Hat Enterprise Linux 4.0');
insert into os_variants values (id_seq.nextval, 'rhel4.1', 'Red Hat Enterprise Linux 4.1');
insert into os_variants values (id_seq.nextval, 'rhel4.2', 'Red Hat Enterprise Linux 4.2');
insert into os_variants values (id_seq.nextval, 'rhel4.3', 'Red Hat Enterprise Linux 4.3');
insert into os_variants values (id_seq.nextval, 'rhel4.4', 'Red Hat Enterprise Linux 4.4');
insert into os_variants values (id_seq.nextval, 'rhel4.5', 'Red Hat Enterprise Linux 4.5');
insert into os_variants values (id_seq.nextval, 'rhel4.6', 'Red Hat Enterprise Linux 4.6');
insert into os_variants values (id_seq.nextval, 'rhel4.7', 'Red Hat Enterprise Linux 4.7');
insert into os_variants values (id_seq.nextval, 'rhel4.8', 'Red Hat Enterprise Linux 4.8');
insert into os_variants values (id_seq.nextval, 'rhel4.9', 'Red Hat Enterprise Linux 4.9');
insert into os_variants values (id_seq.nextval, 'rhel5.0', 'Red Hat Enterprise Linux 5.0');
insert into os_variants values (id_seq.nextval, 'rhel5.1', 'Red Hat Enterprise Linux 5.1');
insert into os_variants values (id_seq.nextval, 'rhel5.10', 'Red Hat Enterprise Linux 5.10');
insert into os_variants values (id_seq.nextval, 'rhel5.11', 'Red Hat Enterprise Linux 5.11');
insert into os_variants values (id_seq.nextval, 'rhel5.2', 'Red Hat Enterprise Linux 5.2');
insert into os_variants values (id_seq.nextval, 'rhel5.3', 'Red Hat Enterprise Linux 5.3');
insert into os_variants values (id_seq.nextval, 'rhel5.4', 'Red Hat Enterprise Linux 5.4');
insert into os_variants values (id_seq.nextval, 'rhel5.5', 'Red Hat Enterprise Linux 5.5');
insert into os_variants values (id_seq.nextval, 'rhel5.6', 'Red Hat Enterprise Linux 5.6');
insert into os_variants values (id_seq.nextval, 'rhel5.7', 'Red Hat Enterprise Linux 5.7');
insert into os_variants values (id_seq.nextval, 'rhel5.8', 'Red Hat Enterprise Linux 5.8');
insert into os_variants values (id_seq.nextval, 'rhel5.9', 'Red Hat Enterprise Linux 5.9');
insert into os_variants values (id_seq.nextval, 'rhel6-unknown', 'Red Hat Enterprise Linux 6 Unknown');
insert into os_variants values (id_seq.nextval, 'rhel6.0', 'Red Hat Enterprise Linux 6.0');
insert into os_variants values (id_seq.nextval, 'rhel6.1', 'Red Hat Enterprise Linux 6.1');
insert into os_variants values (id_seq.nextval, 'rhel6.10', 'Red Hat Enterprise Linux 6.10');
insert into os_variants values (id_seq.nextval, 'rhel6.2', 'Red Hat Enterprise Linux 6.2');
insert into os_variants values (id_seq.nextval, 'rhel6.3', 'Red Hat Enterprise Linux 6.3');
insert into os_variants values (id_seq.nextval, 'rhel6.4', 'Red Hat Enterprise Linux 6.4');
insert into os_variants values (id_seq.nextval, 'rhel6.5', 'Red Hat Enterprise Linux 6.5');
insert into os_variants values (id_seq.nextval, 'rhel6.6', 'Red Hat Enterprise Linux 6.6');
insert into os_variants values (id_seq.nextval, 'rhel6.7', 'Red Hat Enterprise Linux 6.7');
insert into os_variants values (id_seq.nextval, 'rhel6.8', 'Red Hat Enterprise Linux 6.8');
insert into os_variants values (id_seq.nextval, 'rhel6.9', 'Red Hat Enterprise Linux 6.9');
insert into os_variants values (id_seq.nextval, 'rhel7-unknown', 'Red Hat Enterprise Linux 7 Unknown');
insert into os_variants values (id_seq.nextval, 'rhel7.0', 'Red Hat Enterprise Linux 7.0');
insert into os_variants values (id_seq.nextval, 'rhel7.1', 'Red Hat Enterprise Linux 7.1');
insert into os_variants values (id_seq.nextval, 'rhel7.2', 'Red Hat Enterprise Linux 7.2');
insert into os_variants values (id_seq.nextval, 'rhel7.3', 'Red Hat Enterprise Linux 7.3');
insert into os_variants values (id_seq.nextval, 'rhel7.4', 'Red Hat Enterprise Linux 7.4');
insert into os_variants values (id_seq.nextval, 'rhel7.5', 'Red Hat Enterprise Linux 7.5');
insert into os_variants values (id_seq.nextval, 'rhel7.6', 'Red Hat Enterprise Linux 7.6');
insert into os_variants values (id_seq.nextval, 'rhel7.7', 'Red Hat Enterprise Linux 7.7');
insert into os_variants values (id_seq.nextval, 'rhel7.8', 'Red Hat Enterprise Linux 7.8');
insert into os_variants values (id_seq.nextval, 'rhel7.9', 'Red Hat Enterprise Linux 7.9');
insert into os_variants values (id_seq.nextval, 'rhel8-unknown', 'Red Hat Enterprise Linux 8 Unknown');
insert into os_variants values (id_seq.nextval, 'rhel8.0', 'Red Hat Enterprise Linux 8.0');
insert into os_variants values (id_seq.nextval, 'rhel8.1', 'Red Hat Enterprise Linux 8.1');
insert into os_variants values (id_seq.nextval, 'rhel8.10', 'Red Hat Enterprise Linux 8.10');
insert into os_variants values (id_seq.nextval, 'rhel8.2', 'Red Hat Enterprise Linux 8.2');
insert into os_variants values (id_seq.nextval, 'rhel8.3', 'Red Hat Enterprise Linux 8.3');
insert into os_variants values (id_seq.nextval, 'rhel8.4', 'Red Hat Enterprise Linux 8.4');
insert into os_variants values (id_seq.nextval, 'rhel8.5', 'Red Hat Enterprise Linux 8.5');
insert into os_variants values (id_seq.nextval, 'rhel8.6', 'Red Hat Enterprise Linux 8.6');
insert into os_variants values (id_seq.nextval, 'rhel8.7', 'Red Hat Enterprise Linux 8.7');
insert into os_variants values (id_seq.nextval, 'rhel8.8', 'Red Hat Enterprise Linux 8.8');
insert into os_variants values (id_seq.nextval, 'rhel8.9', 'Red Hat Enterprise Linux 8.9');
insert into os_variants values (id_seq.nextval, 'rhel9-unknown', 'Red Hat Enterprise Linux 9 Unknown');
insert into os_variants values (id_seq.nextval, 'rhel9.0', 'Red Hat Enterprise Linux 9.0');
insert into os_variants values (id_seq.nextval, 'rhel9.1', 'Red Hat Enterprise Linux 9.1');
insert into os_variants values (id_seq.nextval, 'rhel9.2', 'Red Hat Enterprise Linux 9.2');
insert into os_variants values (id_seq.nextval, 'rhel9.3', 'Red Hat Enterprise Linux 9.3');
insert into os_variants values (id_seq.nextval, 'rhel9.4', 'Red Hat Enterprise Linux 9.4');
insert into os_variants values (id_seq.nextval, 'rhel9.5', 'Red Hat Enterprise Linux 9.5');
insert into os_variants values (id_seq.nextval, 'rhl1.0', 'Red Hat Linux 1.0');
insert into os_variants values (id_seq.nextval, 'rhl1.1', 'Red Hat Linux 1.1');
insert into os_variants values (id_seq.nextval, 'rhl2.0', 'Red Hat Linux 2.0');
insert into os_variants values (id_seq.nextval, 'rhl2.1', 'Red Hat Linux 2.1');
insert into os_variants values (id_seq.nextval, 'rhl3.0.3', 'Red Hat Linux 3.0.3');
insert into os_variants values (id_seq.nextval, 'rhl4.0', 'Red Hat Linux 4.0');
insert into os_variants values (id_seq.nextval, 'rhl4.1', 'Red Hat Linux 4.1');
insert into os_variants values (id_seq.nextval, 'rhl4.2', 'Red Hat Linux 4.2');
insert into os_variants values (id_seq.nextval, 'rhl5.0', 'Red Hat Linux 5.0');
insert into os_variants values (id_seq.nextval, 'rhl5.1', 'Red Hat Linux 5.1');
insert into os_variants values (id_seq.nextval, 'rhl5.2', 'Red Hat Linux 5.2');
insert into os_variants values (id_seq.nextval, 'rhl6.0', 'Red Hat Linux 6.0');
insert into os_variants values (id_seq.nextval, 'rhl6.1', 'Red Hat Linux 6.1');
insert into os_variants values (id_seq.nextval, 'rhl6.2', 'Red Hat Linux 6.2');
insert into os_variants values (id_seq.nextval, 'rhl7', 'Red Hat Linux 7');
insert into os_variants values (id_seq.nextval, 'rhl7.1', 'Red Hat Linux 7.1');
insert into os_variants values (id_seq.nextval, 'rhl7.2', 'Red Hat Linux 7.2');
insert into os_variants values (id_seq.nextval, 'rhl7.3', 'Red Hat Linux 7.3');
insert into os_variants values (id_seq.nextval, 'rhl8.0', 'Red Hat Linux 8.0');
insert into os_variants values (id_seq.nextval, 'rhl9', 'Red Hat Linux 9');
insert into os_variants values (id_seq.nextval, 'rocky-unknown', 'Rocky Linux Unknown');
insert into os_variants values (id_seq.nextval, 'rocky8', 'Rocky Linux 8');
insert into os_variants values (id_seq.nextval, 'rocky8-unknown', 'Rocky Linux 8 Unknown');
insert into os_variants values (id_seq.nextval, 'rocky8.4', 'Rocky Linux 8.4');
insert into os_variants values (id_seq.nextval, 'rocky8.5', 'Rocky Linux 8.5');
insert into os_variants values (id_seq.nextval, 'rocky8.6', 'Rocky Linux 8.6');
insert into os_variants values (id_seq.nextval, 'rocky9', 'Rocky Linux 9');
insert into os_variants values (id_seq.nextval, 'rocky9-unknown', 'Rocky Linux 9 Unknown');
insert into os_variants values (id_seq.nextval, 'rocky9.0', 'Rocky Linux 9.0');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.0', 'Scientific Linux 5.0');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.1', 'Scientific Linux 5.1');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.10', 'Scientific Linux 5.10');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.11', 'Scientific Linux 5.11');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.2', 'Scientific Linux 5.2');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.3', 'Scientific Linux 5.3');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.4', 'Scientific Linux 5.4');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.5', 'Scientific Linux 5.5');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.6', 'Scientific Linux 5.6');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.7', 'Scientific Linux 5.7');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.8', 'Scientific Linux 5.8');
insert into os_variants values (id_seq.nextval, 'scientificlinux5.9', 'Scientific Linux 5.9');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.0', 'Scientific Linux 6.0');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.1', 'Scientific Linux 6.1');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.10', 'Scientific Linux 6.10');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.2', 'Scientific Linux 6.2');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.3', 'Scientific Linux 6.3');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.4', 'Scientific Linux 6.4');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.5', 'Scientific Linux 6.5');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.6', 'Scientific Linux 6.6');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.7', 'Scientific Linux 6.7');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.8', 'Scientific Linux 6.8');
insert into os_variants values (id_seq.nextval, 'scientificlinux6.9', 'Scientific Linux 6.9');
insert into os_variants values (id_seq.nextval, 'scientificlinux7-unknown', 'Scientific Linux 7 Unknown');
insert into os_variants values (id_seq.nextval, 'scientificlinux7.0', 'Scientific Linux 7.0');
insert into os_variants values (id_seq.nextval, 'scientificlinux7.1', 'Scientific Linux 7.1');
insert into os_variants values (id_seq.nextval, 'scientificlinux7.2', 'Scientific Linux 7.2');
insert into os_variants values (id_seq.nextval, 'scientificlinux7.3', 'Scientific Linux 7.3');
insert into os_variants values (id_seq.nextval, 'scientificlinux7.4', 'Scientific Linux 7.4');
insert into os_variants values (id_seq.nextval, 'scientificlinux7.5', 'Scientific Linux 7.5');
insert into os_variants values (id_seq.nextval, 'scientificlinux7.6', 'Scientific Linux 7.6');
insert into os_variants values (id_seq.nextval, 'silverblue-rawhide', 'Fedora Silverblue Rawhide');
insert into os_variants values (id_seq.nextval, 'silverblue-unknown', 'Fedora Silverblue');
insert into os_variants values (id_seq.nextval, 'silverblue28', 'Fedora Silverblue 28');
insert into os_variants values (id_seq.nextval, 'silverblue29', 'Fedora Silverblue 29');
insert into os_variants values (id_seq.nextval, 'silverblue30', 'Fedora Silverblue 30');
insert into os_variants values (id_seq.nextval, 'silverblue31', 'Fedora Silverblue 31');
insert into os_variants values (id_seq.nextval, 'silverblue32', 'Fedora Silverblue 32');
insert into os_variants values (id_seq.nextval, 'silverblue33', 'Fedora Silverblue 33');
insert into os_variants values (id_seq.nextval, 'silverblue34', 'Fedora Silverblue 34');
insert into os_variants values (id_seq.nextval, 'silverblue35', 'Fedora Silverblue 35');
insert into os_variants values (id_seq.nextval, 'silverblue36', 'Fedora Silverblue 36');
insert into os_variants values (id_seq.nextval, 'silverblue37', 'Fedora Silverblue 37');
insert into os_variants values (id_seq.nextval, 'silverblue38', 'Fedora Silverblue 38');
insert into os_variants values (id_seq.nextval, 'silverblue39', 'Fedora Silverblue 39');
insert into os_variants values (id_seq.nextval, 'silverblue40', 'Fedora Silverblue 40');
insert into os_variants values (id_seq.nextval, 'slackware-current', 'Slackware -current');
insert into os_variants values (id_seq.nextval, 'slackware14.2', 'Slackware 14.2');
insert into os_variants values (id_seq.nextval, 'sle-unknown', 'SUSE Linux Enterprise Unknown');
insert into os_variants values (id_seq.nextval, 'sle15', 'SUSE Linux Enterprise 15');
insert into os_variants values (id_seq.nextval, 'sle15-unknown', 'SUSE Linux Enterprise 15 Unknown');
insert into os_variants values (id_seq.nextval, 'sle15sp1', 'SUSE Linux Enterprise 15 SP1');
insert into os_variants values (id_seq.nextval, 'sle15sp2', 'SUSE Linux Enterprise 15 SP2');
insert into os_variants values (id_seq.nextval, 'sle15sp3', 'SUSE Linux Enterprise 15 SP3');
insert into os_variants values (id_seq.nextval, 'sle15sp4', 'SUSE Linux Enterprise 15 SP4');
insert into os_variants values (id_seq.nextval, 'sle15sp5', 'SUSE Linux Enterprise 15 SP5');
insert into os_variants values (id_seq.nextval, 'sled10', 'SUSE Linux Enterprise Desktop 10');
insert into os_variants values (id_seq.nextval, 'sled10sp1', 'SUSE Linux Enterprise Desktop 10 SP1');
insert into os_variants values (id_seq.nextval, 'sled10sp2', 'SUSE Linux Enterprise Desktop 10 SP2');
insert into os_variants values (id_seq.nextval, 'sled10sp3', 'SUSE Linux Enterprise Desktop 10 SP3');
insert into os_variants values (id_seq.nextval, 'sled10sp4', 'SUSE Linux Enterprise Desktop 10 SP4');
insert into os_variants values (id_seq.nextval, 'sled11', 'SUSE Linux Enterprise Desktop 11');
insert into os_variants values (id_seq.nextval, 'sled11sp1', 'SUSE Linux Enterprise Desktop 11 SP1');
insert into os_variants values (id_seq.nextval, 'sled11sp2', 'SUSE Linux Enterprise Desktop 11 SP2');
insert into os_variants values (id_seq.nextval, 'sled11sp3', 'SUSE Linux Enterprise Desktop 11 SP3');
insert into os_variants values (id_seq.nextval, 'sled11sp4', 'SUSE Linux Enterprise Desktop 11 SP4');
insert into os_variants values (id_seq.nextval, 'sled12', 'SUSE Linux Enterprise Desktop 12');
insert into os_variants values (id_seq.nextval, 'sled12-unknown', 'SUSE Linux Enterprise Desktop 12 Unknown');
insert into os_variants values (id_seq.nextval, 'sled12sp1', 'SUSE Linux Enterprise Desktop 12 SP1');
insert into os_variants values (id_seq.nextval, 'sled12sp2', 'SUSE Linux Enterprise Desktop 12 SP2');
insert into os_variants values (id_seq.nextval, 'sled12sp3', 'SUSE Linux Enterprise Desktop 12 SP3');
insert into os_variants values (id_seq.nextval, 'sled12sp4', 'SUSE Linux Enterprise Desktop 12 SP4');
insert into os_variants values (id_seq.nextval, 'sled12sp5', 'SUSE Linux Enterprise Desktop 12 SP5');
insert into os_variants values (id_seq.nextval, 'sled9', 'SUSE Linux Enterprise Desktop 9');
insert into os_variants values (id_seq.nextval, 'slem5.0', 'SUSE Linux Enterprise Micro');
insert into os_variants values (id_seq.nextval, 'slem5.1', 'SUSE Linux Enterprise Micro 5.1');
insert into os_variants values (id_seq.nextval, 'slem5.2', 'SUSE Linux Enterprise Micro 5.2');
insert into os_variants values (id_seq.nextval, 'slem5.3', 'SUSE Linux Enterprise Micro 5.3');
insert into os_variants values (id_seq.nextval, 'slem5.4', 'SUSE Linux Enterprise Micro 5.4');
insert into os_variants values (id_seq.nextval, 'sles10', 'SUSE Linux Enterprise Server 10');
insert into os_variants values (id_seq.nextval, 'sles10sp1', 'SUSE Linux Enterprise Server 10 SP1');
insert into os_variants values (id_seq.nextval, 'sles10sp2', 'SUSE Linux Enterprise Server 10 SP2');
insert into os_variants values (id_seq.nextval, 'sles10sp3', 'SUSE Linux Enterprise Server 10 SP3');
insert into os_variants values (id_seq.nextval, 'sles10sp4', 'SUSE Linux Enterprise Server 10 SP4');
insert into os_variants values (id_seq.nextval, 'sles11', 'SUSE Linux Enterprise Server 11');
insert into os_variants values (id_seq.nextval, 'sles11sp1', 'SUSE Linux Enterprise Server 11 SP1');
insert into os_variants values (id_seq.nextval, 'sles11sp2', 'SUSE Linux Enterprise Server 11 SP2');
insert into os_variants values (id_seq.nextval, 'sles11sp3', 'SUSE Linux Enterprise Server 11 SP3');
insert into os_variants values (id_seq.nextval, 'sles11sp4', 'SUSE Linux Enterprise Server 11 SP4');
insert into os_variants values (id_seq.nextval, 'sles12', 'SUSE Linux Enterprise Server 12');
insert into os_variants values (id_seq.nextval, 'sles12-unknown', 'SUSE Linux Enterprise Server 12 Unknown');
insert into os_variants values (id_seq.nextval, 'sles12sp1', 'SUSE Linux Enterprise Server 12 SP1');
insert into os_variants values (id_seq.nextval, 'sles12sp2', 'SUSE Linux Enterprise Server 12 SP2');
insert into os_variants values (id_seq.nextval, 'sles12sp3', 'SUSE Linux Enterprise Server 12 SP3');
insert into os_variants values (id_seq.nextval, 'sles12sp4', 'SUSE Linux Enterprise Server 12 SP4');
insert into os_variants values (id_seq.nextval, 'sles12sp5', 'SUSE Linux Enterprise Server 12 SP5');
insert into os_variants values (id_seq.nextval, 'sles9', 'SUSE Linux Enterprise Server 9');
insert into os_variants values (id_seq.nextval, 'smartos', 'Triton SmartOS');
insert into os_variants values (id_seq.nextval, 'solaris10', 'Solaris 10');
insert into os_variants values (id_seq.nextval, 'solaris11', 'Oracle Solaris 11');
insert into os_variants values (id_seq.nextval, 'solaris9', 'Solaris 9');
insert into os_variants values (id_seq.nextval, 'trisquel10', 'Trisquel 10.0 LTS');
insert into os_variants values (id_seq.nextval, 'trisquel11', 'Trisquel 11.0 LTS');
insert into os_variants values (id_seq.nextval, 'trisquel9', 'Trisquel 9.0 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu10.04', 'Ubuntu 10.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu10.10', 'Ubuntu 10.10');
insert into os_variants values (id_seq.nextval, 'ubuntu11.04', 'Ubuntu 11.04');
insert into os_variants values (id_seq.nextval, 'ubuntu11.10', 'Ubuntu 11.10');
insert into os_variants values (id_seq.nextval, 'ubuntu12.04', 'Ubuntu 12.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu12.10', 'Ubuntu 12.10');
insert into os_variants values (id_seq.nextval, 'ubuntu13.04', 'Ubuntu 13.04');
insert into os_variants values (id_seq.nextval, 'ubuntu13.10', 'Ubuntu 13.10');
insert into os_variants values (id_seq.nextval, 'ubuntu14.04', 'Ubuntu 14.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu14.10', 'Ubuntu 14.10');
insert into os_variants values (id_seq.nextval, 'ubuntu15.04', 'Ubuntu 15.04');
insert into os_variants values (id_seq.nextval, 'ubuntu15.10', 'Ubuntu 15.10');
insert into os_variants values (id_seq.nextval, 'ubuntu16.04', 'Ubuntu 16.04');
insert into os_variants values (id_seq.nextval, 'ubuntu16.10', 'Ubuntu 16.10');
insert into os_variants values (id_seq.nextval, 'ubuntu17.04', 'Ubuntu 17.04');
insert into os_variants values (id_seq.nextval, 'ubuntu17.10', 'Ubuntu 17.10');
insert into os_variants values (id_seq.nextval, 'ubuntu18.04', 'Ubuntu 18.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu18.10', 'Ubuntu 18.10');
insert into os_variants values (id_seq.nextval, 'ubuntu19.04', 'Ubuntu 19.04');
insert into os_variants values (id_seq.nextval, 'ubuntu19.10', 'Ubuntu 19.10');
insert into os_variants values (id_seq.nextval, 'ubuntu20.04', 'Ubuntu 20.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu20.10', 'Ubuntu 20.10');
insert into os_variants values (id_seq.nextval, 'ubuntu21.04', 'Ubuntu 21.04');
insert into os_variants values (id_seq.nextval, 'ubuntu21.10', 'Ubuntu 21.10');
insert into os_variants values (id_seq.nextval, 'ubuntu22.04', 'Ubuntu 22.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu22.10', 'Ubuntu 22.10');
insert into os_variants values (id_seq.nextval, 'ubuntu23.04', 'Ubuntu 23.04');
insert into os_variants values (id_seq.nextval, 'ubuntu23.10', 'Ubuntu 23.10');
insert into os_variants values (id_seq.nextval, 'ubuntu24.04', 'Ubuntu 24.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu24.10', 'Ubuntu 24.10');
insert into os_variants values (id_seq.nextval, 'ubuntu4.10', 'Ubuntu 4.10');
insert into os_variants values (id_seq.nextval, 'ubuntu5.04', 'Ubuntu 5.04');
insert into os_variants values (id_seq.nextval, 'ubuntu5.10', 'Ubuntu 5.10');
insert into os_variants values (id_seq.nextval, 'ubuntu6.06', 'Ubuntu 6.06 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu6.10', 'Ubuntu 6.10');
insert into os_variants values (id_seq.nextval, 'ubuntu7.04', 'Ubuntu 7.04');
insert into os_variants values (id_seq.nextval, 'ubuntu7.10', 'Ubuntu 7.10');
insert into os_variants values (id_seq.nextval, 'ubuntu8.04', 'Ubuntu 8.04 LTS');
insert into os_variants values (id_seq.nextval, 'ubuntu8.10', 'Ubuntu 8.10');
insert into os_variants values (id_seq.nextval, 'ubuntu9.04', 'Ubuntu 9.04');
insert into os_variants values (id_seq.nextval, 'ubuntu9.10', 'Ubuntu 9.10');
insert into os_variants values (id_seq.nextval, 'ucs4.0', 'Univention Corporate Server 4.0');
insert into os_variants values (id_seq.nextval, 'ucs4.1', 'Univention Corporate Server 4.1');
insert into os_variants values (id_seq.nextval, 'ucs4.2', 'Univention Corporate Server 4.2');
insert into os_variants values (id_seq.nextval, 'ucs4.3', 'Univention Corporate Server 4.3');
insert into os_variants values (id_seq.nextval, 'ucs4.4', 'Univention Corporate Server 4.4');
insert into os_variants values (id_seq.nextval, 'ucs5.0', 'Univention Corporate Server 5.0');
insert into os_variants values (id_seq.nextval, 'unknown', 'Unknown');
insert into os_variants values (id_seq.nextval, 'voidlinux', 'Void Linux');
insert into os_variants values (id_seq.nextval, 'win1.0', 'Microsoft Windows 1.0');
insert into os_variants values (id_seq.nextval, 'win10', 'Microsoft Windows 10');
insert into os_variants values (id_seq.nextval, 'win11', 'Microsoft Windows 11');
insert into os_variants values (id_seq.nextval, 'win2.0', 'Microsoft Windows 2.0');
insert into os_variants values (id_seq.nextval, 'win2.1', 'Microsoft Windows 2.1');
insert into os_variants values (id_seq.nextval, 'win2k', 'Microsoft Windows 2000');
insert into os_variants values (id_seq.nextval, 'win2k12', 'Microsoft Windows Server 2012');
insert into os_variants values (id_seq.nextval, 'win2k12r2', 'Microsoft Windows Server 2012 R2');
insert into os_variants values (id_seq.nextval, 'win2k16', 'Microsoft Windows Server 2016');
insert into os_variants values (id_seq.nextval, 'win2k19', 'Microsoft Windows Server 2019');
insert into os_variants values (id_seq.nextval, 'win2k22', 'Microsoft Windows Server 2022');
insert into os_variants values (id_seq.nextval, 'win2k3', 'Microsoft Windows Server 2003');
insert into os_variants values (id_seq.nextval, 'win2k3r2', 'Microsoft Windows Server 2003 R2');
insert into os_variants values (id_seq.nextval, 'win2k8', 'Microsoft Windows Server 2008');
insert into os_variants values (id_seq.nextval, 'win2k8r2', 'Microsoft Windows Server 2008 R2');
insert into os_variants values (id_seq.nextval, 'win3.1', 'Microsoft Windows 3.1');
insert into os_variants values (id_seq.nextval, 'win7', 'Microsoft Windows 7');
insert into os_variants values (id_seq.nextval, 'win8', 'Microsoft Windows 8');
insert into os_variants values (id_seq.nextval, 'win8.1', 'Microsoft Windows 8.1');
insert into os_variants values (id_seq.nextval, 'win95', 'Microsoft Windows 95');
insert into os_variants values (id_seq.nextval, 'win98', 'Microsoft Windows 98');
insert into os_variants values (id_seq.nextval, 'winme', 'Microsoft Windows Millennium Edition');
insert into os_variants values (id_seq.nextval, 'winnt3.1', 'Microsoft Windows NT Server 3.1');
insert into os_variants values (id_seq.nextval, 'winnt3.5', 'Microsoft Windows NT Server 3.5');
insert into os_variants values (id_seq.nextval, 'winnt3.51', 'Microsoft Windows NT Server 3.51');
insert into os_variants values (id_seq.nextval, 'winnt4.0', 'Microsoft Windows NT Server 4.0');
insert into os_variants values (id_seq.nextval, 'winvista', 'Microsoft Windows Vista');
insert into os_variants values (id_seq.nextval, 'winxp', 'Microsoft Windows XP');
