"use server"

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import { getListOfVirtualMachines } from "@/utls/serverActions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function getMetadata()
{
  return metadata;
}

export default async function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) 
{
  const vmList = await getListOfVirtualMachines();
  console.log(vmList);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
